"""Add indexes to chat_list

Revision ID: d6fccdb6af74
Revises: 
Create Date: 2024-02-22 17:12:22.822005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fccdb6af74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_list_favorite_order', 'chat_list', ['favorite', 'favorite_order', 'created_at'], unique=False)
    op.create_index('idx_chat_list_user_id_is_del', 'chat_list', ['user_id', 'is_del'], unique=False)
    op.create_index(op.f('ix_chat_list_favorite_order'), 'chat_list', ['favorite_order'], unique=False)
    op.create_index(op.f('ix_chat_list_img_url'), 'chat_list', ['img_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_list_img_url'), table_name='chat_list')
    op.drop_index(op.f('ix_chat_list_favorite_order'), table_name='chat_list')
    op.drop_index('idx_chat_list_user_id_is_del', table_name='chat_list')
    op.drop_index('idx_chat_list_favorite_order', table_name='chat_list')
    # ### end Alembic commands ###
