"""[user table] used_message added

Revision ID: e94dbea657fe
Revises: d6fccdb6af74
Create Date: 2024-02-29 10:23:05.959759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94dbea657fe'
down_revision: Union[str, None] = 'd6fccdb6af74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('used_message', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'used_message')
    # ### end Alembic commands ###
