"""user table upd
ated

Revision ID: 26d42e879ad4
Revises: 54db7d50e42c
Create Date: 2024-07-13 23:11:11.096690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d42e879ad4'
down_revision: Union[str, None] = '54db7d50e42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_test', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('experiment', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_experiment'), 'user', ['experiment'], unique=False)
    op.create_index(op.f('ix_user_is_test'), 'user', ['is_test'], unique=False)
    op.create_index(op.f('ix_user_subscribed'), 'user', ['subscribed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscribed'), table_name='user')
    op.drop_index(op.f('ix_user_is_test'), table_name='user')
    op.drop_index(op.f('ix_user_experiment'), table_name='user')
    op.drop_column('user', 'experiment')
    op.drop_column('user', 'is_test')
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###
