"""description of changes

Revision ID: c888456a7ebc
Revises: 
Create Date: 2023-10-10 00:32:24.872497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c888456a7ebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import String, MetaData, Table


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # user_id 타입 변경
    op.alter_column('store_log', 'user_id', type_=String(100))

    # platform 컬럼 삭제
    op.drop_column('store_log', 'platform')

    # type 컬럼 타입 변경
    op.alter_column('store_log', 'type', type_=String(50))

 